
openapi: 3.0.3
info:
  title: Saksbehandling
  description: This is a sample description about this spec.
  termsOfService: ''
  contact:
    email: ''
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about spec
  url: ''
servers: []
tags:
  - name: Default
    description: ''
paths:
  /behandlinger/:
    get:
      summary: Gir en liste med planer
      description: ''
      operationId: ''
      tags: [ ]
      parameters: &ref_0 [ ]
      requestBody: { }
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: $ref
                  $ref: '#/components/schemas/Behandlingsplan'
  /behandlinger/{hubbaId}:
    get:
      summary: Gir en konkret hubba tilbake
      description: ''
      operationId: ''
      tags: [ ]
      parameters: *ref_0
      requestBody:
        content: { }
      responses:
        '200':
          content:
            application/json:
              schema:
                type: $ref
                $ref: '#/components/schemas/Hubba'
  /behandlinger/{hubbaId}/steg/{stegId}:
    put:
      summary: Løs et hubbasteg
      description: ''
      operationId: ''
      tags: [ ]
      parameters:
        - in: path
          name: planId
          description: ''
          schema: &ref_1
            type: string
          required: true
        - in: path
          name: stegId
          description: ''
          schema: *ref_1
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                svar:
                  type: string
                  description: Svar/løsning på steget
                begrunnelse:
                  type: string
                  description: Begrunnelse for svaret
              required:
                - svar
      responses:
        '200':
          content:
            application/json:
              schema:
                type: $ref
                $ref: '#/components/schemas/Behandlingssteg'
components:
  schemas:
    Hubba:
      type: object
      properties:
        gjelder:
          type: string
          description: Hvilken entitet gjelder denne planen
        steg:
          type: array
          items:
            type: $ref
            $ref: '#/components/schemas/Hubbasteg'
          description: Stegene i planen
        status:
          type: string
          description: Ferdig/Ikke ferdig
        saksbehandler:
          type: string
          description: Saksbehandler
        datoOpprettet:
          type: string
        hendelse:
          type: $ref
          $ref: '#/components/schemas/Hendelse'
      description: En behandling
      required:
        - gjelder
        - steg
        - saksbehandler
        - datoOpprettet
        - hendelse
    Hubbasteg:
      type: object
      properties:
        id:
          type: string
          description: ID til trinnet
        type:
          type: string
          description: Hva slags type trinn det er (vilkår/fastsett)
        tilstand:
          type: string
          description: IkkeUtført/Utført
      required:
        - id
        - type
        - tilstand
    Hendelse:
      type: object
      properties:
        id:
          type: string
        masse greier:
          type: string
      required:
        - id
        - masse greier
  securitySchemes: {}
