apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    domene: behandling
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{ ingresses }}
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: FLYWAY_CLEAN_DISABLED
      value: "false"
    - name: DP_IVERKSETT_URL
      value: {{dp-iverksett.url}}
    - name: DP_IVERKSETT_SCOPE
      value: {{dp-iverksett.scope}}
    - name: AAREG_URL
      value: {{aareg.url}}
    - name: AAREG_SCOPE
      value: {{aareg.scope}}
    - name: GRUPPE_SAKSBEHANDLER
      value: {{azure.grupper.saksbehandler}}
    - name: GRUPPE_BESLUTTER
      value: {{azure.grupper.beslutter}}
  azure:
    application:
      enabled: true
      tenant: {{ azure.tenant }}
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
        extra:
          - NAVident
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: {{gcp.sql.tier}}
        databases:
          - name: behandling
            envVarPrefix: DB
  accessPolicy:
    outbound:
      rules:
        - application: dp-iverksett
      external:
        - host: aareg-services-q2.dev-fss-pub.nais.io
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        {{#if wonderwalled}}
        - application: wonderwalled-azure
          namespace: aura
        {{/if}}