apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-saksbehandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    domene: behandling
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{ ingresses }}
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=50.0 -XX:ActiveProcessorCount=4 -XX:+PrintFlagsFinal
    - name: FLYWAY_CLEAN_DISABLED
      value: "false"
    - name: GRUPPE_SAKSBEHANDLER
      value: {{azure.grupper.saksbehandler}}
    - name: GRUPPE_BESLUTTER
      value: {{azure.grupper.beslutter}}
    - name: GRUPPE_EGNE_ANSATTE
      value: {{azure.grupper.egne_ansatte}}
    - name: GRUPPE_FORTROLIG
      value: {{azure.grupper.adressebeskyttelse_fortrolig}}
    - name: GRUPPE_STRENGT_FORTROLIG
      value: {{azure.grupper.adressebeskyttelse_strengt_fortrolig}}
    - name: GRUPPE_STRENGT_FORTROLIG_UTLAND
      value: {{azure.grupper.adressebeskyttelse_strengt_fortrolig_utland}}
    - name: PDL_API_URL
      value: https://{{pdl.host}}
    - name: PDL_API_SCOPE
      value: {{pdl.scope}}
    - name: SKJERMING_API_URL
      value: {{skjerming.url}}
    - name: SKJERMING_API_SCOPE
      value: {{skjerming.scope}}
    - name: JOURNALPOSTID_API_SCOOPE
      value: {{ journalpostid.scope }}
  azure:
    application:
      enabled: true
      tenant: {{ azure.tenant }}
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
          - id: {{azure.grupper.egne_ansatte}}
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        {{#if wonderwalled}}
        - application: wonderwalled-azure
          namespace: aura
        - application: azure-token-generator
          namespace: aura
        {{/if}}
    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
        - application: dp-oppslag-journalpost-id
          namespace: teamdagpenger
      external:
        - host: {{pdl.host}}
  gcp:
    sqlInstances:
      - collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: saksbehandling
        diskAutoresize: true
        diskType: SSD
        highAvailability: {{ db.highAvailability }}
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        pointInTimeRecovery: {{ db.pointInTimeRecovery }}
        tier: {{ db.tier }}
        type: POSTGRES_15
