apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-saksbehandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    domene: behandling
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{ ingresses }}
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: FLYWAY_CLEAN_DISABLED
      value: "false"
    - name: GRUPPE_SAKSBEHANDLER
      value: {{azure.grupper.saksbehandler}}
    - name: GRUPPE_BESLUTTER
      value: {{azure.grupper.beslutter}}
  azure:
    application:
      enabled: true
      tenant: {{ azure.tenant }}
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        {{#if wonderwalled}}
        - application: wonderwalled-azure
          namespace: aura
        - application: azure-token-generator
          namespace: aura
        {{/if}}
    outbound:
      rules:
        - application: dp-behandling