apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    domene: behandling
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{ ingresses }}
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: CLEAN_DISABLED
      value: "false"
  azure:
    application:
      enabled: true
      tenant: {{ azure.tenant }}
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
        extra:
          - NAVident
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: {{gcp.sql.tier}}
        databases:
          - name: behandling
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        {{#if wonderwalled}}
        - application: wonderwalled-azure
          namespace: aura
        {{/if}}