apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-saksbehandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    domene: behandling
spec:
  image: "{{ image }}"
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  leaderElection: true
  replicas:
    min: 3
    max: 3
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{ ingresses }}
  secureLogs:
    enabled: true
  kafka:
    pool: "{{ kafka_pool }}"
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=50.0 -XX:ActiveProcessorCount=4 -XX:+PrintFlagsFinal
    - name: FLYWAY_CLEAN_DISABLED
      value: "false"
    - name: GRUPPE_SAKSBEHANDLER
      value: "{{azure.grupper.saksbehandler}}"
    - name: GRUPPE_BESLUTTER
      value: "{{azure.grupper.beslutter}}"
    - name: GRUPPE_EGNE_ANSATTE
      value: "{{azure.grupper.egne_ansatte}}"
    - name: GRUPPE_FORTROLIG
      value: "{{azure.grupper.adressebeskyttelse_fortrolig}}"
    - name: GRUPPE_STRENGT_FORTROLIG
      value: "{{azure.grupper.adressebeskyttelse_strengt_fortrolig}}"
    - name: GRUPPE_STRENGT_FORTROLIG_UTLAND
      value: "{{azure.grupper.adressebeskyttelse_strengt_fortrolig_utland}}"
    - name: PDL_API_URL
      value: https://{{pdl.host}}
    - name: PDL_API_SCOPE
      value: "{{pdl.scope}}"
    - name: SKJERMING_API_URL
      value: "{{skjerming.url}}"
    - name: SKJERMING_API_SCOPE
      value: "{{skjerming.scope}}"
    - name: DP_MOTTAK_API_SCOPE
      value: "{{ dp-mottak.scope }}"
    - name: DP_BEHANDLING_API_SCOPE
      value: "{{ dp-behandling.scope }}"
    - name: DP_MELDING_OM_VEDTAK_API_SCOPE
      value: "{{ dp-melding-om-vedtak.scope }}"

  azure:
    application:
      enabled: true
      tenant: "{{ azure.tenant }}"
      claims:
        groups:
          - id: "{{azure.grupper.saksbehandler}}"
          - id: "{{azure.grupper.beslutter}}"
          - id: "{{azure.grupper.egne_ansatte}}"
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: dp-mottak
        - application: dp-melding-om-vedtak
        - application: dp-saksbehandling-frontend
        - application: dp-mellom-barken-og-veden
        {{#if wonderwalled}}
        - application: wonderwalled-azure
          namespace: nais
        - application: azure-token-generator
          namespace: nais
        {{/if}}
    outbound:
      rules:
        - application: dp-behandling
        - application: dp-melding-om-vedtak
        - application: dp-mottak
        - application: skjermede-personer-pip
          namespace: nom
        - application: norg2
          namespace: org
      external:
        - host: "{{pdl.host}}"
        - host: graph.microsoft.com
  gcp:
    sqlInstances:
      - collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: saksbehandling
        diskAutoresize: true
        diskType: SSD
        highAvailability: {{ db.highAvailability }}
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        pointInTimeRecovery: {{ db.pointInTimeRecovery }}
        tier: "{{ db.tier }}"
        type: POSTGRES_15
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
