package no.nav.dagpenger.saksbehandling.klage

enum class OpplysningType(
    val navn: String,
    val datatype: Datatype,
    val påkrevd: Boolean = true,
    val valgmuligheter: List<String> = emptyList(),
) {
    // Klagen gjelder
    KLAGEN_GJELDER(
        navn = "Hva klagen gjelder",
        datatype = Datatype.FLERVALG,
        påkrevd = false,
        valgmuligheter = listOf("Avslag på søknad", "Dagpengenes størrelse", "Annet"),
    ),
    KLAGEN_GJELDER_VEDTAK(
        navn = "Vedtak klagen gjelder",
        datatype = Datatype.TEKST,
    ),

    // Formkrav
    ER_KLAGEN_SKRIFTLIG(
        navn = "Er klagen skriftlig?",
        datatype = Datatype.BOOLSK,
    ),
    ER_KLAGEN_UNDERSKREVET(
        navn = "Er klagen underskrevet?",
        datatype = Datatype.BOOLSK,
    ),
    KLAGEN_NEVNER_ENDRING(
        navn = "Nevner klagen den endring som kreves?",
        datatype = Datatype.BOOLSK,
    ),
    RETTSLIG_KLAGEINTERESSE(
        navn = "Har klager rettslig klageinteresse?",
        datatype = Datatype.BOOLSK,
    ),

    // Klagefrist
    KLAGE_MOTTATT(
        navn = "Klage mottatt",
        datatype = Datatype.DATO,
    ),
    KLAGEFRIST(
        navn = "Frist for å klage",
        datatype = Datatype.DATO,
    ),
    KLAGEFRIST_OPPFYLT(
        navn = "Har klager klaget innen fristen?",
        datatype = Datatype.BOOLSK,
    ),

    // Oversittet frist
    OPPREISNING_OVERSITTET_FRIST(
        navn = "Gis klager oppreisning for oversittet frist?",
        datatype = Datatype.BOOLSK,
    ),

    OPPREISNING_OVERSITTET_FRIST_BEGRUNNELSE(
        navn = "Begrunnelse",
        datatype = Datatype.TEKST,
    ),

    // Utfall
    UTFALL(
        navn = "Utfall",
        datatype = Datatype.TEKST,
        valgmuligheter = UtfallType.entries.map { it.name },
    ),

    VURDERING_AV_KLAGEN(
        navn = "Vurdering av klagen",
        datatype = Datatype.TEKST,
    ),

    // Info til klageinstans del 1
    HVEM_KLAGER(
        navn = "Hvem er klager i saken?",
        datatype = Datatype.TEKST,
        valgmuligheter = HvemKlagerType.entries.map { it.name },
    ),

    // Info til klageinstans del 2
    HJEMLER(
        navn = "Hvilke hjemler gjelder klagen?",
        datatype = Datatype.FLERVALG,
        valgmuligheter = Hjemler.entries.map { it.name },
    ),
    INTERN_MELDING(
        navn = "Intern melding",
        datatype = Datatype.TEKST,
        påkrevd = false,
    ),

    // Info til klageinstans om fullmektig
    FULLMEKTIG_NAVN(
        navn = "Navn",
        datatype = Datatype.TEKST,
    ),
    FULLMEKTIG_ADRESSE_1(
        navn = "Adresselinje 1",
        datatype = Datatype.TEKST,
    ),
    FULLMEKTIG_ADRESSE_2(
        navn = "Adresselinje 2",
        datatype = Datatype.TEKST,
        påkrevd = false,
    ),
    FULLMEKTIG_ADRESSE_3(
        navn = "Adresselinje 3",
        datatype = Datatype.TEKST,
        påkrevd = false,
    ),
    FULLMEKTIG_POSTNR(
        navn = "Postnummer",
        datatype = Datatype.TEKST,
    ),
    FULLMEKTIG_POSTSTED(
        navn = "Poststed",
        datatype = Datatype.TEKST,
    ),
    FULLMEKTIG_LAND(
        navn = "Land",
        datatype = Datatype.TEKST,
        valgmuligheter = Land.entries.map { it.name },
    ),
}

enum class Datatype {
    TEKST,
    DATO,
    BOOLSK,
    FLERVALG,
}

enum class UtfallType {
    OPPRETTHOLDELSE,
    MEDHOLD,
    DELVIS_MEDHOLD,
    AVVIST,
}

enum class HvemKlagerType {
    BRUKER,
    FULLMEKTIG,
}

enum class KlagenGjelderType {
    AVSLAG_PÅ_SØKNAD,
    DAGPENGENES_STØRRELSE,
    ANNET,
}

enum class Hjemler {
    FTRL_4_2,
    FTRL_4_3_1,
    FTRL_4_3_1_PERMLL,
    FTRL_4_3_2,
    FTRL_4_4,
    FTRL_4_5_REGISTRERING,
    FTRL_4_5_REELL_ARBEIDSSOEKER,
    FTRL_4_6_UTDANNING,
    FTRL_4_6_ETABLERING,
    FTRL_4_7_PERMITTERINGSAARSAK,
    FTRL_4_7_PERMITTERINGENS_LENGDE,
    FTRL_4_8,
    FTRL_4_9,
    FTRL_4_10,
    FTRL_4_11,
    FTRL_4_12,
    FTRL_4_13,
    FTRL_4_14,
    FTRL_4_15,
    FTRL_4_16,
    FTRL_4_18,
    FTRL_4_19,
    FTRL_4_20,
    FTRL_4_22,
    FTRL_4_23,
    FTRL_4_24,
    FTRL_4_25,
    FTRL_4_26,
    FTRL_4_27,
    FTRL_4_28,
}

// TODO: Vurder om vi burde importere et bibliotek/kodeverk som dekker behovet vårt her.
// det blir for mye styr å opprettholde dette når det er mange nye land :)
enum class Land(land: String) {
    AD("Andorra"),
    AE("De forente arabiske emirater"),
    AF("Afghanistan"),
    AG("Antigua og Barbuda"),
    AI("Anguilla"),
    AL("Albania"),
    AM("Armenia"),
    AO("Angola"),
    AQ("Antarktis"),
    AR("Argentina"),
    AS("Amerikansk Samoa"),
    AT("Østerrike"),
    AU("Australia"),
    AW("Aruba"),
    AX("Åland"),
    AZ("Aserbajdsjan"),
    BA("Bosnia-Hercegovina"),
    BB("Barbados"),
    BD("Bangladesh"),
    BE("Belgia"),
    BF("Burkina Faso"),
    BG("Bulgaria"),
    BH("Bahrain"),
    BI("Burundi"),
    BJ("Benin"),
    BL("Saint-Barthélemy"),
    BM("Bermuda"),
    BN("Brunei"),
    BO("Bolivia"),
    BQ("Bonaire, Sint Eustatius og Saba"),
    BR("Brasil"),
    BS("Bahamas"),
    BT("Bhutan"),
    BV("Bouvetøya"),
    BW("Botswana"),
    BY("Belarus"),
    BZ("Belize"),
    CA("Canada"),
    CC("Kokosøyene"),
    CD("Den demokratiske republikken Kongo"),
    CF("Den sentralafrikanske republikk"),
    CG("Republikken Kongo"),
    CH("Sveits"),
    CI("Elfenbenskysten"),
    CK("Cookøyene"),
    CL("Chile"),
    CM("Kamerun"),
    CN("Kina"),
    CO("Colombia"),
    CR("Costa Rica"),
    // CS Serbia og Montenegro er ikke i bruk lengre
    // men Folkeregisteret har personer med gjeldende statsborkerskap eller fødeland her.
    // Dermed er koden i felles kodeverk.
    CS("Serbia og Montenegro"),

    CU("Cuba"),
    CV("Kapp Verde"),
    CW("Curaçao"),
    CX("Christmasøya"),
    CY("Kypros"),
    CZ("Tsjekkia"),
    DE("Tyskland"),
    DJ("Djibouti"),
    DK("Danmark"),
    DM("Dominica"),
    DO("Den dominikanske republikk"),
    DZ("Algerie"),
    EC("Ecuador"),
    EE("Estland"),
    EG("Egypt"),
    EH("Vest-Sahara"),
    ER("Eritrea"),
    ES("Spania"),
    ET("Etiopia"),
    FI("Finland"),
    FJ("Fiji"),
    FK("Falklandsøyene"),
    FM("Mikronesiaføderasjonen"),
    FO("Færøyene"),
    FR("Frankrike"),
    GA("Gabon"),
    GB("Storbritannia"),
    GD("Grenada"),
    GE("Georgia"),
    GF("Fransk Guyana"),
    GG("Guernsey"),
    GH("Ghana"),
    GI("Gibraltar"),
    GL("Grønland"),
    GM("Gambia"),
    GN("Guinea"),
    GP("Guadeloupe"),
    GQ("Ekvatorial-Guinea"),
    GR("Hellas"),
    GS("Sør-Georgia og Sør-Sandwichøyene"),
    GT("Guatemala"),
    GU("Guam"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HK("Hongkong"),
    HM("Heard- og McDonaldøyene"),
    HN("Honduras"),
    HR("Kroatia"),
    HT("Haiti"),
    HU("Ungarn"),
    ID("Indonesia"),
    IE("Irland"),
    IL("Israel"),
    IM("Man"),
    IN("India"),
    IO("Det britiske territoriet i Indiahavet"),
    IQ("Irak"),
    IR("Iran"),
    IS("Island"),
    IT("Italia"),
    JE("Jersey"),
    JM("Jamaica"),
    JO("Jordan"),
    JP("Japan"),
    KE("Kenya"),
    KG("Kirgisistan"),
    KH("Kambodsja"),
    KI("Kiribati"),
    KM("Komorene"),
    KN("Saint Kitts og Nevis"),
    KP("Nord-Korea"),
    KR("Sør-Korea"),
    KW("Kuwait"),
    KY("Caymanøyene"),
    KZ("Kasakhstan"),
    LA("Laos"),
    LB("Libanon"),
    LC("Saint Lucia"),
    LI("Liechtenstein"),
    LK("Sri Lanka"),
    LR("Liberia"),
    LS("Lesotho"),
    LT("Litauen"),
    LU("Luxembourg"),
    LV("Latvia"),
    LY("Libya"),
    MA("Marokko"),
    MC("Monaco"),
    MD("Moldova"),
    ME("Montenegro"),
    MF("Saint-Martin"),
    MG("Madagaskar"),
    MH("Marshalløyene"),
    MK("Nord-Makedonia"),
    ML("Mali"),
    MM("Myanmar"),
    MN("Mongolia"),
    MO("Macao"),
    MP("Nord-Marianene"),
    MQ("Martinique"),
    MR("Mauritania"),
    MS("Montserrat"),
    MT("Malta"),
    MU("Mauritius"),
    MV("Maldivene"),
    MW("Malawi"),
    MX("Mexico"),
    MY("Malaysia"),
    MZ("Mosambik"),
    NA("Namibia"),
    NC("Ny-Caledonia"),
    NE("Niger"),
    NF("Norfolkøya"),
    NG("Nigeria"),
    NI("Nicaragua"),
    NL("Nederland"),
    NO("Norge"),
    NP("Nepal"),
    NR("Nauru"),
    NU("Niue"),
    NZ("New Zealand"),
    OM("Oman"),
    PA("Panama"),
    PE("Peru"),
    PF("Fransk Polynesia"),
    PG("Papua Ny-Guinea"),
    PH("Filippinene"),
    PK("Pakistan"),
    PL("Polen"),
    PM("Saint-Pierre og Miquelon"),
    PN("Pitcairnøyene"),
    PR("Puerto Rico"),
    PS("Palestina"),
    PT("Portugal"),
    PW("Palau"),
    PY("Paraguay"),
    QA("Qatar"),
    RE("Réunion"),
    RO("Romania"),
    RS("Serbia"),
    RU("Russland"),
    RW("Rwanda"),
    SA("Saudi-Arabia"),
    SB("Salomonøyene"),
    SC("Seychellene"),
    SD("Sudan"),
    SE("Sverige"),
    SG("Singapore"),
    SH("St. Helena, Ascension og Tristan da Cunha"),
    SI("Slovenia"),
    SJ("Svalbard og Jan Mayen"),
    SK("Slovakia"),
    SL("Sierra Leone"),
    SM("San Marino"),
    SN("Senegal"),
    SO("Somalia"),
    SR("Surinam"),
    SS("Sør-Sudan"),
    ST("São Tomé og Príncipe"),
    SV("El Salvador"),
    SX("Sint Maarten"),
    SY("Syria"),
    SZ("Swaziland"),
    TC("Turks- og Caicosøyene"),
    TD("Tsjad"),
    // Ikke inkludert i felles kodeverk
    // TF("De franske sørterritorier"),
    TG("Togo"),
    TH("Thailand"),
    TJ("Tadsjikistan"),
    TK("Tokelau"),
    TL("Øst-Timor"),
    TM("Turkmenistan"),
    TN("Tunisia"),
    TO("Tonga"),
    TR("Tyrkia"),
    TT("Trinidad og Tobago"),
    TV("Tuvalu"),
    TW("Taiwan"),
    TZ("Tanzania"),
    UA("Ukraina"),
    UG("Uganda"),
    UM("USAs ytre småøyer"),
    US("USA"),
    UY("Uruguay"),
    UZ("Usbekistan"),
    VA("Vatikanstaten"),
    VC("Saint Vincent og Grenadinene"),
    VE("Venezuela"),
    VG("De britiske Jomfruøyer"),
    VI("De amerikanske Jomfruøyer"),
    VN("Vietnam"),
    VU("Vanuatu"),
    WF("Wallis og Futuna"),
    WS("Samoa"),
    // X* koder er "brukerkoder".
    // SSB og felles kodeverk definerer XB Kanariøyene og XK Kosovo.
    XB("Kanariøyene"),
    XK("Kosovo"),

    YE("Jemen"),
    YT("Mayotte"),
    ZA("Sør-Afrika"),
    ZM("Zambia"),
    ZW("Zimbabwe"),
}
