openapi: 3.0.0
info:
  title: Behandling API
  version: 1.0.0
  description: API for å hente alle behandlinger.
  contact:
    name: '#team-dagpenger'
servers:
  - url: https://dp-behandling.intern.dev.nav.no
    description: dev
  - url: https://dp-behandling.intern.nav.no
    description: prod
paths:
  /behandling:
    post:
      description: Hent alle behandlinger for en gitt person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentForesporsel'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Behandling'


    get:
      summary: Hent alle behandlinger for en gitt person
      security:
        - azureAd: [ ]
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Behandling'
          description: OK
  /behandling/{behandlingId}:
    parameters:
      - name: behandlingId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Behandlingens id
    get:
      summary: Hent en spesifikk behandling
      security:
        - azureAd: [ ]
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Behandling'
          description: OK
  /behandling/{behandlingId}/opplysning/{opplysningId}:
    parameters:
      - name: behandlingId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Behandlingens id
      - name: opplysningId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Opplysningens id
    put:
      summary: Overskriv en opplysning
      operationId: oppdaterOpplysning
      security:
        - azureAd: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - verdi
                - begrunnelse
              properties:
                verdi:
                  type: string
                begrunnelse:
                  type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Behandling'
          description: OK
  /behandling/{behandlingId}/opplysning/bekreftelse:
    parameters:
      - name: behandlingId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Behandlingens id
    post:
      summary: Bekrefter en eller flere opplysninger
      security:
        - azureAd: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OpplysningsId'
      responses:
        201:
          headers:
            Location:
              schema:
                type: string
                description: URL til bekreftelsen
          description: OK
  /behandling/{behandlingId}/opplysning/bekreftelse/{bekreftelseId}:
    parameters:
      - name: behandlingId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Behandlingens id
      - name: bekreftelseId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Bekreftelsens id
    get:
      summary: Hent en bekreftelse
      security:
        - azureAd: [ ]
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bekreftelse'
          description: OK

components:
  schemas:
    IdentForesporsel:
      type: object
      required:
        - ident
      properties:
        ident:
          type: string
    Ramme:
      type: object
      properties:
        vedtakId:
          type: string
          format: uuid
        virkningsdato:
          type: string
          format: date
      required:
        - vedtakId
        - virkningsdato
    Utbetaling:
      type: object
      properties:
        vedtakId:
          type: string
          format: uuid
        fraOgMed:
          type: string
          format: date
        tilOgMed:
          type: string
          format: date
        sumUtbetalt:
          type: number
          format: double
      required:
        - vedtakId
        - fraOgMed
        - tilOgMed
    Vedtak:
      type: object
      required:
        - rammer
        - utbetalinger
      properties:
        rammer:
          type: array
          items:
            $ref: '#/components/schemas/Ramme'
        utbetalinger:
          type: array
          items:
            $ref: '#/components/schemas/Utbetaling'

    Behandling:
      type: object
      required:
        - behandlingId
        - opplysning
        - utbetalinger
      properties:
        behandlingId:
          type: string
          format: uuid
        opplysning:
          type: array
          items:
            $ref: '#/components/schemas/Opplysning'

    OpplysningsId:
      type: string
      format: uuid

    Opplysning:
      type: object
      required:
        - id
        - opplysningstype
        - verdi
        - datatype
        - status
        - gyldigFraOgMed
        - gyldigTilOgMed
        - redigerbar
      properties:
        id:
          $ref: '#/components/schemas/OpplysningsId'
        opplysningstype:
          type: string
        verdi:
          type: string
        status:
          type: string
          enum: [ "Hypotese", "Faktum" ]
        gyldigFraOgMed:
          type: string
          format: date-time
        gyldigTilOgMed:
          type: string
          format: date-time
        datatype:
          type: string
          description: |
            Hvilken datatype opplysningen har, f.eks.: "string", "number", "date"
        redigerbar:
          type: boolean
          description: Indikerer om opplysningen kan redigeres
        kilde:
          oneOf:
            - $ref: '#/components/schemas/Systemkilde'
            - $ref: '#/components/schemas/Saksbehandlerkilde'
          discriminator:
            propertyName: type
        utledetAv:
          $ref: '#/components/schemas/Utledning'

    Opplysningskilde:
      description: |
        Kilde for opplysningen
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type

    Saksbehandlerkilde:
      allOf:
        - $ref: "#/components/schemas/Opplysningskilde"
        - $ref: '#/components/schemas/Saksbehandler'

    Systemkilde:
      allOf:
        - $ref: "#/components/schemas/Opplysningskilde"
        - type: object
          required:
            - id
          properties:
            id:
              type: string
          example:
            id: "dp-inntekt"

    Utledning:
      type: object
      required:
        - produserer
        - regel
        - opplysninger
      properties:
        opplysningstype:
          type: string
        regel:
          $ref: '#/components/schemas/Regel'
        opplysninger:
          type: array
          items:
            $ref: '#/components/schemas/Opplysning'

    Regel:
      type: object
      required:
        - navn
      properties:
        navn:
          type: string

    Bekreftelse:
      type: object
      required:
        - bekreftelseId
        - bekreftet
      properties:
        bekreftelseId:
          type: string
          format: uuid
        utført:
          type: string
          format: date-time
        saksbehandler:
          $ref: "#/components/schemas/Saksbehandler"
        bekreftet:
          type: array
          items:
            $ref: '#/components/schemas/OpplysningsId'

    Saksbehandler:
      type: object
      required:
        - ident
      properties:
        ident:
          type: string

  securitySchemes:
    azureAd:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bruker [AzureAD](https://docs.nais.io/security/auth/azure-ad) til autentisering. 
        Token må ha `audience` satt til `[cluster].teamdagpenger.dp-behandling`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
        - [dev-gcp](https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp.teamdagpenger.dp-behandling)