FROM europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/jre:openjdk-21@sha256:e0c34ea2a1c7d4e6e8a3f584aebb2ea412ee6845a6cac5b02061bba472707066

ENV LANG='nb_NO.UTF-8' LANGUAGE='nb_NO:nb' LC_ALL='nb_NO.UTF-8' TZ="Europe/Oslo"

COPY build/libs/mediator-all.jar /app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]