openapi: 3.0.3
info:
  title: Saksbehandling API
  version: 1.0.0
  description: Et API for å administrere oppgaver og deres tilstandsoverganger.
servers:
  - url: https://dp-saksbehandling.intern.dev.nav.no
    description: dev
  - url: https://dp-saksbehandling # Service discovery internt i clusteret
    description: prod
paths:
  /oppgave:
    get:
      summary: Hent alle oppgaver
      responses:
        '200':
          description: Vellykket respons med en liste over oppgaver
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OppgaveOversikt'
  /oppgave/mine:
    get:
      summary: Hent alle saksbehandlers oppgaver under behandling
      responses:
        '200':
          description: Vellykket respons med en liste over oppgaver som saksbehandler har under behandling
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OppgaveOversikt'
  /oppgave/sok:
    post:
      summary: Søk etter oppgaver ved hjelp av fødselsnummer (FNR)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sok'
      responses:
        '200':
          description: Vellykket respons med en liste over oppgaver som samsvarer med FNR-en
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OppgaveOversikt'
  /oppgave/{oppgaveId}:
    get:
      summary: Hent en oppgave ved hjelp av dens ID
      parameters:
        - in: path
          name: oppgaveId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Vellykket respons med detaljer om oppgaven
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Oppgave'
        '404':
          description: Oppgaven ble ikke funnet

  /oppgave/{oppgaveId}/tildel:
    put:
      summary: Saksbehandler blir tildelt ansvaret for oppgaven
      parameters:
        - in: path
          name: oppgaveId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Vellykket respons med detaljer om oppgaven
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Oppgave'
        '404':
          description: Oppgaven ble ikke funnet
        '423':
          description: Oppgaven er allerede tatt til behandling
  /oppgave/{oppgaveId}/leggTilbake:
    put:
      summary: Saksbehandler fjernes som ansvarlig for oppgaven, og oppgaven går tilbake til oppgavelisten
      parameters:
        - in: path
          name: oppgaveId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Fjernet saksbehandler som ansvarlig for oppgaven, og oppgaven gjøres klar til behandling
components:
  schemas:
    Person:
      type: object
      properties:
        ident:
          type: string
        fornavn:
          type: string
        etternavn:
          type: string
        mellomnavn:
          type: string
        fodselsdato:
          type: date
        alder:
          type: integer
        statsborgerskap:
          type: string
        kjonn:
          $ref: '#/components/schemas/Kjonn'
      required:
        - ident
        - fornavn
        - etternavn
        - fodselsdato
        - alder
        - kjonn

    OppgaveOversikt:
      type: object
      properties:
        oppgaveId:
          type: string
          format: uuid
        behandlingId:
          type: string
          format: uuid
        personIdent:
          type: string
        tidspunktOpprettet:
          type: string
          format: date-time
        emneknagger:
          type: array
          items:
            type: string
        tilstand:
          $ref: '#/components/schemas/OppgaveTilstand'
      required:
        - oppgaveId
        - behandlingId
        - personIdent
        - tidspunktOpprettet
        - tilstand
        - emneknagger

    Oppgave:
      type: object
      properties:
        oppgaveId:
          type: string
          format: uuid
        behandlingId:
          type: string
          format: uuid
        personIdent:
          type: string
        person:
          $ref: '#/components/schemas/Person'
        tidspunktOpprettet:
          type: string
          format: date-time
        journalpostIder:
          type: array
          items:
            type: string
        emneknagger:
          type: array
          items:
            type: string
        tilstand:
          $ref: '#/components/schemas/OppgaveTilstand'
      required:
        - oppgaveId
        - behandlingId
        - personIdent
        - person
        - tidspunktOpprettet
        - tilstand
        - emneknagger

    Kjonn:
      type: string
      enum:
        - MANN
        - KVINNE
        - UKJENT

    OppgaveTilstand:
      type: string
      enum:
        - OPPRETTET
        - KLAR_TIL_BEHANDLING
        - UNDER_BEHANDLING
        - FERDIG_BEHANDLET

    Sok:
      type: object
      properties:
        fnr:
          type: string
      required:
        - fnr
