openapi: 3.0.3
info:
  title: Saksbehandling API
  version: 1.0.0
  description: Et API for å administrere oppgaver og deres tilstandsoverganger.
servers:
  - url: https://dp-saksbehandling.intern.dev.nav.no
    description: dev
  - url: https://dp-saksbehandling # Service discovery internt i clusteret
    description: prod
paths:
  /oppgave:
    get:
      summary: Hent alle oppgaver
      responses:
        '200':
          description: Vellykket respons med en liste over oppgaver
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Oppgave'
  /oppgave/sok:
    post:
      summary: Søk etter oppgaver ved hjelp av fødselsnummer (FNR)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sok'
      responses:
        '200':
          description: Vellykket respons med en liste over oppgaver som samsvarer med FNR-en
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Oppgave'
  /oppgave/{oppgaveId}:
    get:
      summary: Hent en oppgave ved hjelp av dens ID
      parameters:
        - in: path
          name: oppgaveId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Vellykket respons med detaljer om oppgaven
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Oppgave'
        '404':
          description: Oppgaven ble ikke funnet

  /oppgave/{oppgaveId}/steg/{stegId}:
    put:
      summary: Besvar opplysninger knyttet til et steg i en oppgave.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Opplysninger'
      parameters:
        - in: path
          name: oppgaveId
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: stegId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Vellykket oppdatering av opplysninger i et steg
        '404':
          description: Oppgaven eller steget ble ikke funnet

  /oppgave/{oppgaveId}/avslag:
    put:
      summary: Avslå søknad om dagpenger. Fungerer kun for avslag på minsteinntekt.
      parameters:
        - in: path
          name: oppgaveId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Vellykket respons
        '404':
          description: Oppgaven ble ikke funnet

  /oppgave/{oppgaveId}/lukk:
    put:
      summary: Lukk en oppgave ved hjelp av dens ID
      parameters:
        - in: path
          name: oppgaveId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Vellykket respons
        '404':
          description: Oppgaven ble ikke funnet

components:
  schemas:
    Oppgave:
      type: object
      properties:
        oppgaveId:
          type: string
          format: uuid
        behandlingId:
          type: string
          format: uuid
        personIdent:
          type: string
        datoOpprettet:
          type: string
          format: date
        journalpostIder:
          type: array
          items:
            type: string
        emneknagger:
          type: array
          items:
            type: string
        tilstand:
          $ref: '#/components/schemas/OppgaveTilstand'
        steg:
          type: array
          items:
            $ref: '#/components/schemas/Steg'
      required:
        - oppgaveId
        - behandlingId
        - personIdent
        - datoOpprettet
        - tilstand
        - steg
        - emneknagger
    OppgaveTilstand:
      type: string
      enum:
        - TilBehandling
        - FerdigBehandlet
    Steg:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        stegNavn:
          type: string
        opplysninger:
          $ref: '#/components/schemas/Opplysninger'
        tilstand:
          $ref: '#/components/schemas/StegTilstand'

      required:
        - uuid
        - stegNavn
        - opplysninger

    Opplysninger:
      type: array
      items:
        $ref: '#/components/schemas/Opplysning'

    Opplysning:
      type: object
      properties:
        opplysningNavn:
          type: string
        opplysningType:
          $ref: '#/components/schemas/OpplysningType'
        svar:
          $ref: '#/components/schemas/Svar'
          nullable: true
    Svar:
      type: object
      properties:
        verdi:
          type: string
          nullable: false
    OpplysningType:
      type: string
      enum:
        - String
        - LocalDate
        - Int
        - Boolean
        - Double
    Sok:
      type: object
      properties:
        fnr:
          type: string
      required:
        - fnr
    StegTilstand:
      type: string
      enum:
        - Groenn
        - Roed
        - Gul
