ALTER TABLE IF EXISTS oppgave_v1
    ADD COLUMN IF NOT EXISTS kontrollert_brev TEXT NOT NULL DEFAULT 'IKKE_RELEVANT';

ALTER TABLE IF EXISTS oppgave_v1
    ALTER COLUMN kontrollert_brev DROP DEFAULT;
